export const FIND_SIMILAR = 'FIND_SIMILAR'
export const FIND_SIMILAR_START = 'FIND_SIMILAR_START'
export const FIND_SIMILAR_FAIL = 'FIND_SIMILAR_FAIL'
export const FIND_SIMILAR_SUCCESS = 'FIND_SIMILAR_SUCCESS'
